<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgvnAoO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgvnAoO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgvnAoO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgvnAoO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgvnAoO\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgvnAoO',
    'container.build_id' => '23b5962b',
    'container.build_time' => 1605782753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgvnAoO');
