<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIKHxOsC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIKHxOsC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIKHxOsC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIKHxOsC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIKHxOsC\App_KernelDevDebugContainer([
    'container.build_hash' => 'IKHxOsC',
    'container.build_id' => '7d32100a',
    'container.build_time' => 1606382941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIKHxOsC');
