<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerIKHxOsC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIKHxOsC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIKHxOsC.legacy');
=======
if (\class_exists(\Container9SjQsro\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9SjQsro/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9SjQsro.legacy');
>>>>>>> 5dcc1f8f085ee197c996394503fcfa7c32b399df

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerIKHxOsC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIKHxOsC\App_KernelDevDebugContainer([
    'container.build_hash' => 'IKHxOsC',
    'container.build_id' => '7d32100a',
    'container.build_time' => 1606382941,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIKHxOsC');
=======
    \class_alias(\Container9SjQsro\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9SjQsro\App_KernelDevDebugContainer([
    'container.build_hash' => '9SjQsro',
    'container.build_id' => '5dd9c158',
    'container.build_time' => 1606376526,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9SjQsro');
>>>>>>> 5dcc1f8f085ee197c996394503fcfa7c32b399df
