<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9SjQsro\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9SjQsro/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9SjQsro.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9SjQsro\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9SjQsro\App_KernelDevDebugContainer([
    'container.build_hash' => '9SjQsro',
    'container.build_id' => '5dd9c158',
    'container.build_time' => 1606376526,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9SjQsro');
